name: Release

on:
  release:
    types: [published]

jobs:
  validate-hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin

  release:
    name: Build & Upload Release
    needs: validate-hacs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install esbuild
        run: npm install esbuild --global

      - name: Minify JS files
        run: |
          mkdir -p dist
          esbuild entity-progress-card.js --minify --outfile=dist/entity-progress-card.min.js

      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: Clean up dist folder
        run: rm -rf dist
