name: Release Processing

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: Minify JS & Upload Assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Copy sources to temp
        run: |
          mkdir temp
          cp *.js temp/

      - name: Clean debugLog calls and function
        run: |
          set -euo pipefail
          SED_INPLACE="sed -i"
        
          for file in temp/*.js; do
            patterns=(
              '/this\.[_#]log = initLogger(/,/]);/d'                      # Remove multi-line initLogger assignments
              '/this\.[_#]log = initLogger/d'                             # Remove single-line initLogger assignments
              '/this\.[_#]log = Logger\.create/d'                         # Remove Logger.create assignments
              '/[_#]log = null;/d'                                        # Remove null log declarations
              '/this\.[_#]log\.debug/d'                                   # Remove debug calls
              '/[_#]debug = CARD\.config\.debug\./d'                      # Remove debug variable assignments
              '/static [_#]debug = CARD\.config\.debug\./d'               # Remove static debug variable assignments
              '/^const Logger = {$/,/^};$/d'                              # Remove Logger class block
              '/^function initLogger(/,/^}$/d'                            # Remove initLogger function block
            )
        
            for pattern in "${patterns[@]}"; do
              $SED_INPLACE "$pattern" "$file"
            done
        
            $SED_INPLACE 's/debug: { card: [^,]*, editor: [^,]*, interactionHandler: [^,]*, ressourceManager: [^,]*, hass: [^}]* }/debug: { card: false, editor: false, interactionHandler: false, ressourceManager: false, hass: false }/g' "$file"
            $SED_INPLACE 's/^[[:space:]]*dev: true,$/    dev: false,/g' "$file"
            $SED_INPLACE '/^$/N;/^\n$/d' "$file"
          done

      - name: Process JS Files
        run: npx esbuild temp/*.js --minify --target=es2022 --outdir=dist

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
