name: Minify JS & Upload Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Minify JS & Upload Release
    needs: validate-hacs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install esbuild
        run: npm install esbuild --global
      - name: Minify JS
        run: |
          mkdir -p dist
          esbuild *.js --minify --outdir=dist
      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
