name: Manage stale issues

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          days-before-stale: 15
          stale-issue-label: 'inactive'
          remove-stale-when-updated: true
          stale-issue-message: |
            This issue has been inactive for 15 days. It will be closed in 15 days if no further activity occurs.

          days-before-close: 15
          close-issue-message: >
            Closing this issue due to inactivity after warning period.
            No worries though — if you still need assistance or want to continue the discussion, 
            just reply here and we’ll gladly reopen the issue and pick things back up with you!
  
          exempt-issue-labels: 'pinned'

          stale-pr-message: ''
          operations-per-run: 30
